import test from'node:test';import assert from'node:assert/strict';
import {analyzeMatch,distribution,redactAnalytics,aggregateReports,toCsv,entropy}from'../shared/analytics.js';
import {createMatchState,advanceState}from'../shared/match.js';import{getJevCandidates}from'../shared/sudoku-ai.js';import{validateClientEvent}from'../server/telemetry.js';
const puzzle='004678912672195348198342567859761423426853791713924856961537284287419635345286179';
const initial={givens:puzzle,config:createMatchState(puzzle,{mode:'ranked',pacingMs:1000}).config};
const events=[{type:'start',ms:0,sequence:1},{type:'human',ms:200,sequence:2,action:{kind:'set',cell:0,digit:5}},{type:'human',ms:500,sequence:3,action:{kind:'clear',cell:0}},{type:'human',ms:800,sequence:4,action:{kind:'undo'}},{type:'human',ms:1200,sequence:5,action:{kind:'set',cell:1,digit:3}},{type:'settle',ms:2000,sequence:6}];
test('exact gameplay metric accounting and empty-denominator behavior',()=>{const r=analyzeMatch(initial,events);assert.equal(r.human.acceptedActions,4);assert.equal(r.human.placements,2);assert.equal(r.human.clears,1);assert.equal(r.human.undos,1);assert.equal(r.human.cellEdits[0],3);assert.equal(r.human.cellEdits[1],1);assert.equal(r.human.editEfficiency,.5);assert.equal(r.game.humanFinishMs,1200);assert.equal(r.human.moveIntervalsMs.median,300);assert.equal(r.jev.estimatedCostUsd,null);assert.equal(r.jev.requestErrorRate,null);});
test('percentiles, standard deviation and entropy are reproducible',()=>{const d=distribution([1,2,3,4]);assert.equal(d.median,2.5);assert.ok(Math.abs(d.p95-3.85)<1e-9);assert.equal(distribution([]).mean,null);assert.equal(entropy({a:.5,b:.5}),1);});
test('client telemetry is separated from server evidence and never changes score',()=>{const t=[{trust:'client',name:'cell_focus',properties:{cell:0,durationMs:1000}},{trust:'client',name:'note_added',properties:{cell:1}},{trust:'server',name:'action_rejected',properties:{reason:'local_conflict'}}];const r=analyzeMatch(initial,events,t);assert.equal(r.game.humanFinishMs,1200);assert.equal(r.browser.focusDwellMs,1000);assert.equal(r.browser.notesAdded,1);assert.equal(r.human.localConflictRejections,1);});
test('cost estimates require configured prices and complete reported token usage',()=>{const t=[{trust:'server',name:'jev_request_finished',properties:{outcome:'ok',latencyMs:15,inputTokens:1000,outputTokens:20}}];const r=analyzeMatch(initial,events,t,{inputUsdPerMillion:2,outputUsdPerMillion:0});assert.equal(r.jev.estimatedCostUsd,.002);const unknown=structuredClone(t);unknown[0].properties.inputTokens=null;assert.equal(analyzeMatch(initial,events,unknown,{inputUsdPerMillion:2,outputUsdPerMillion:0}).jev.estimatedCostUsd,null);});
test('redaction strips coordinates, digits, action IDs, probabilities and evidence',()=>{let s=createMatchState(puzzle,initial.config);s=advanceState(s,{type:'start',ms:0});const a=getJevCandidates(s.jev,'normal').candidates[0];const r=analyzeMatch(initial,[{type:'start',ms:0,sequence:1},{type:'jev',ms:1000,sequence:2,action:a,decision:{source:'forced',confidence:1,probabilities:{[a.id]:1},candidateEvidence:[a]}}]);const safe=redactAnalytics(r,true);for(const k of ['cell','digit','actionId','proof','probabilities','candidateEvidence'])assert.equal(safe.jev.decisions[0][k],undefined);assert.equal(safe.jev.decisions[0].technique,'naked_single');});
test('summary separates difficulties and records streaks',()=>{const r=analyzeMatch(initial,events);const s=aggregateReports([r,r]);assert.equal(s.games,2);assert.equal(s.wins,2);assert.equal(s.bestWinStreak,2);assert.equal(s.perDifficulty.normal.completed,2);});
test('telemetry schema rejects arbitrary text, keys, timestamps and forged event names',()=>{assert.equal(validateClientEvent({id:'abcdefgh',name:'cell_focus',properties:{cell:1,durationMs:2}}).properties.cell,1);for(const e of [{id:'abcdefgh',name:'jev_request_finished',properties:{}},{id:'abcdefgh',name:'cell_focus',properties:{cell:81,durationMs:1}},{id:'abcdefgh',name:'cell_focus',properties:{cell:1,durationMs:1,secret:'no'}}])assert.throws(()=>validateClientEvent(e));});
test('CSV safely escapes commas, quotes, newlines and spreadsheet formulas',()=>{const csv=toCsv([{name:'=HYPERLINK("bad")',n:null},{name:'a,b\nc',n:12}],['name','n']);assert.ok(csv.includes("'="));assert.ok(csv.includes('""bad""'));assert.ok(csv.includes('"a,b\nc"'));});

test('voided attempts are not wins, losses, draws, or completion-rate denominator',()=>{
  const good=analyzeMatch(initial,events),voided=analyzeMatch(initial,[{type:'void',ms:0,reason:'expired_reservation'}]);
  const s=aggregateReports([good,voided]);assert.equal(s.games,2);assert.equal(s.finished,2);assert.equal(s.validFinished,1);assert.equal(s.voided,1);assert.equal(s.draws,0);assert.equal(s.winRate,1);
});
