import test from'node:test';import assert from'node:assert/strict';import {createApp}from'../server/server.js';import{loadConfig}from'../server/config.js';import{openDb}from'../server/db.js';import{hash}from'../server/security.js';
async function setup(){const cfg={...loadConfig({LAUNCH_SIGNING_KEY:'b'.repeat(64)}),port:0},app=createApp({config:cfg,db:openDb(':memory:'),autoTick:false});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));cfg.origin=`http://127.0.0.1:${app.server.address().port}`;const response=await fetch(`${cfg.origin}/api/me`),me=await response.json(),cookie=response.headers.get('set-cookie').split(';')[0];return {...app,base:cfg.origin,me,cookie,req:async(path,{method='GET',body,csrf=true,auth=true,origin=cfg.origin}={})=>fetch(`${cfg.origin}${path}`,{method,headers:{...(auth?{Cookie:cookie}:{}),...(body!==undefined?{'Content-Type':'application/json',Origin:origin,...(csrf?{'X-CSRF-Token':me.csrfToken}:{})}:{})},body:body===undefined?undefined:JSON.stringify(body)})};}
test('HTTP security headers, static assets, and unauthenticated boundaries',async()=>{const x=await setup();try{const r=await x.req('/');assert.equal(r.status,200);assert.ok(r.headers.get('content-security-policy').includes("frame-ancestors 'none'"));assert.ok((await r.text()).includes('Sudoku Duel'));assert.equal((await x.req('/server/config.js')).status,404);assert.equal((await x.req('/api/analytics/me',{auth:false})).status,401);assert.equal((await x.req('/api/analytics/operator')).status,403);assert.equal((await x.req('/api/matches',{method:'POST',csrf:false,body:{requestId:'abcdefghi'}})).status,403);assert.equal((await x.req('/api/matches',{method:'POST',origin:'https://evil.test',body:{requestId:'abcdefghi'}})).status,403);}finally{await x.close();}});
test('HTTP create/start/action/analytics and strict ownership',async()=>{const x=await setup();try{const reserved=await x.req('/api/matches',{method:'POST',body:{requestId:'test-create-123',difficulty:'normal',mode:'practice'}});assert.equal(reserved.status,201);const p=await reserved.json();assert.equal(p.givens,null);const started=await(await x.req(`/api/matches/${p.id}/start`,{method:'POST',body:{}})).json();assert.equal(started.givens.length,81);assert.equal(started.opponent,'Local heuristic');const a=await x.req(`/api/matches/${p.id}/actions`,{method:'POST',body:{requestId:'forfeit-test-1',expectedHumanRevision:0,action:{kind:'forfeit'}}});assert.equal(a.status,200);const final=await a.json();assert.equal(final.phase,'finished');assert.equal(final.verified,true);const metrics=await(await x.req(`/api/matches/${p.id}/analytics`)).json();assert.equal(metrics.human.forfeits,1);const csv=await x.req(`/api/matches/${p.id}/analytics?format=csv`);assert.equal(csv.status,200);assert.ok(csv.headers.get('content-type').startsWith('text/csv'));const replay=await x.req(`/api/matches/${p.id}/replay`);assert.equal(replay.status,200);const other=await fetch(x.base+'/api/me');const otherCookie=other.headers.get('set-cookie').split(';')[0];const denied=await fetch(x.base+`/api/matches/${p.id}/analytics`,{headers:{Cookie:otherCookie}});assert.equal(denied.status,403);}finally{await x.close();}});
test('telemetry requires consent, validates event allowlist, and can be purged',async()=>{const x=await setup();try{const p=await(await x.req('/api/matches',{method:'POST',body:{requestId:'telemetry-create',mode:'practice'}})).json();const event={id:'test-event-123',name:'note_added',properties:{cell:2}};
  assert.equal((await x.req(`/api/matches/${p.id}/telemetry`,{method:'POST',body:{events:[event]}})).status,403);
  assert.equal((await x.req('/api/privacy',{method:'POST',body:{telemetryConsent:true}})).status,200);
  assert.equal((await x.req(`/api/matches/${p.id}/telemetry`,{method:'POST',body:{events:[event,event]}})).status,200);assert.equal(x.db.prepare("SELECT COUNT(*) n FROM telemetry WHERE trust='client'").get().n,1);
  assert.equal((await x.req(`/api/matches/${p.id}/telemetry`,{method:'POST',body:{events:[{...event,name:'game_completed'}]}})).status,422);
  await x.req('/api/privacy',{method:'POST',body:{telemetryConsent:false}});assert.equal(x.db.prepare("SELECT COUNT(*) n FROM telemetry WHERE trust='client'").get().n,0);
}finally{await x.close();}});
test('data export does not expose running ranked initial data or server keys',async()=>{const x=await setup();try{const response=await x.req('/api/me/export');assert.equal(response.status,200);const text=await response.text();assert.equal(text.includes('launchKey'),false);assert.equal(text.includes('csrfToken'),false);assert.equal((await x.req('/api/me/data',{method:'DELETE',body:{confirm:'wrong'}})).status,422);assert.equal((await x.req('/api/me/data',{method:'DELETE',body:{confirm:'DELETE MY DATA'}})).status,200);assert.equal((await x.req('/api/analytics/me')).status,401);}finally{await x.close();}});

test('native HTTP SSE sends authoritative state and closes cleanly',async()=>{
  const x=await setup(),controller=new AbortController();let reader;
  try{
    const p=await(await x.req('/api/matches',{method:'POST',body:{requestId:'native-sse-create',mode:'practice'}})).json();
    await x.req(`/api/matches/${p.id}/start`,{method:'POST',body:{}});
    const stream=await fetch(`${x.base}/api/matches/${p.id}/events`,{headers:{Cookie:x.cookie},signal:controller.signal});
    assert.equal(stream.status,200);assert.equal(stream.headers.get('content-type'),'text/event-stream');
    reader=stream.body.getReader();const first=new TextDecoder().decode((await reader.read()).value);
    assert.ok(first.includes('event: state'));assert.ok(first.includes('"phase":"running"'));
    await x.req(`/api/matches/${p.id}/actions`,{method:'POST',body:{requestId:'native-sse-forfeit',expectedHumanRevision:0,action:{kind:'forfeit'}}});
    const second=new TextDecoder().decode((await reader.read()).value);assert.ok(second.includes('"phase":"finished"'));
  }finally{controller.abort();await reader?.cancel().catch(()=>{});await x.close();}
});
