import test from'node:test';import assert from'node:assert/strict';
import {JevAdapter,validateResponse,encodeJevState}from'../server/jev.js';import{createMatchState}from'../public/shared/match.js';import{getJevCandidates}from'../public/shared/sudoku-ai.js';
const givens='530070000600195000098000060800060003400803001700020006060000280000419005000080079';
const state=createMatchState(givens),bundle=getJevCandidates(state.jev,'normal'),c=bundle.candidates;
const config={jevKey:'test-secret',jevModel:'jev-1.13.0',jevEndpoint:'https://invalid.test',timeoutMs:30};
const payload=()=>({model:config.jevModel,answers:{next_action:{type:'choice',choice:c[0].id,confidence:1,probabilities:Object.fromEntries(c.map((a,i)=>[a.id,i?0:1]))}},usage:{input_tokens:100,output_tokens:20}});
const params={board:state.jev,givens:state.givens,bundle,matchId:'test'};
test('valid structured choice and state encoding excludes human information',()=>{const result=validateResponse(payload(),c,config.jevModel);assert.equal(result.actionId,c[0].id);const encoded=encodeJevState(state.jev,state.givens,c);assert.equal(encoded.human,undefined);assert.equal(encoded.solution,undefined);assert.equal(encoded.values.length,9);assert.equal(encoded.candidates.length,c.length);});
test('probability distribution, confidence, model, IDs and usage are strict',()=>{const mutations=[p=>p.model='other',p=>p.answers.next_action.choice='invented',p=>p.answers.next_action.confidence=2,p=>p.answers.next_action.probabilities[c[0].id]=NaN,p=>p.answers.next_action.probabilities[c[0].id]=.3,p=>p.answers.next_action.probabilities.extra=0,p=>p.usage.input_tokens=-1,p=>delete p.answers.next_action];for(const mutate of mutations){const p=payload();mutate(p);assert.throws(()=>validateResponse(p,c,config.jevModel));}});
test('equal top probabilities use canonical action ID, not provider tie choice',()=>{const p=payload();const ids=c.map(x=>x.id).sort();p.answers.next_action.probabilities=Object.fromEntries(ids.map((id,i)=>[id,i<2?.5:0]));p.answers.next_action.choice=ids[1];assert.equal(validateResponse(p,c,config.jevModel).actionId,ids[0]);});
test('adapter sends the documented shape, records latency and token usage',async()=>{let req;const observations=[];const adapter=new JevAdapter(config,{fetchImpl:async(url,options)=>{req={url,...options};return Response.json(payload());},onRequest:o=>observations.push(o)});const result=await adapter.choose(params);assert.equal(result.source,'jev');assert.equal(result.model,config.jevModel);assert.equal(JSON.parse(req.body).questions.next_action.type,'choice');assert.equal(req.headers.Authorization,'Bearer test-secret');assert.equal(observations[0].properties.inputTokens,100);});
test('malformed output retries once then explicit heuristic fallback',async()=>{let calls=0;const adapter=new JevAdapter(config,{fetchImpl:async()=>{calls++;return Response.json({model:'wrong'});}});const result=await adapter.choose(params);assert.equal(calls,2);assert.equal(result.source,'heuristic_fallback');assert.equal(result.reason,'wrong_model');});
test('timeout is bounded and produces explicit fallback',async()=>{const adapter=new JevAdapter(config,{fetchImpl:async(_,o)=>new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(new Error('aborted'))))});const result=await adapter.choose(params);assert.equal(result.reason,'timeout');assert.equal(result.attempts,2);});
test('authentication failure and long Retry-After are not hammered',async()=>{for(const status of [401,429]){let count=0;const a=new JevAdapter(config,{fetchImpl:async()=>{count++;return new Response('',{status,headers:{'retry-after':'60'}});}});const r=await a.choose(params);assert.equal(count,1);assert.equal(r.source,'heuristic_fallback');}});
test('missing credentials, forced steps, and quota refusals are explicit',async()=>{const noKey=new JevAdapter({...config,jevKey:''});assert.equal((await noKey.choose(params)).source,'heuristic');const forced=new JevAdapter(config);assert.equal((await forced.choose({...params,bundle:{...bundle,candidates:[c[0]]}})).source,'forced');
  let calls=0;const denied=new JevAdapter(config,{reserve:async()=>false,fetchImpl:async()=>{calls++;return Response.json(payload());}});const r=await denied.choose(params);assert.equal(r.source,'heuristic_fallback');assert.equal(r.reason,'provider_quota_limit');assert.equal(r.attempts,0);assert.equal(calls,0,'a refused reservation never reaches the provider');});
test('every provider attempt, including the retry, reserves quota first',async()=>{let reservations=0,calls=0;const adapter=new JevAdapter(config,{reserve:async()=>{reservations++;return true;},fetchImpl:async()=>{calls++;return Response.json({model:'wrong'});}});await adapter.choose(params);assert.equal(reservations,2);assert.equal(calls,2);
  let budget=1;const limited=new JevAdapter(config,{reserve:async()=>budget-->0,fetchImpl:async()=>{calls++;return Response.json({model:'wrong'});}});calls=0;const r=await limited.choose(params);assert.equal(calls,1);assert.equal(r.reason,'provider_quota_limit');assert.equal(r.attempts,1);});
test('the encoded request and evidence never contain the solution grid or human information',async()=>{const adapter=new JevAdapter(config,{fetchImpl:async(_,o)=>{const sent=o.body;for(const banned of ['solution','human','undo','elapsed'])assert.equal(sent.includes(`"${banned}`),false,banned);return Response.json(payload());}});const r=await adapter.choose(params);assert.equal(r.source,'jev');assert.equal(typeof r.stateHash,'string');assert.equal(r.stateHash.length,64);});

/** The provider reports probabilities on a 0.01 grain, so a real distribution never sums to
 *  exactly 1. payload() above returns an exact one-hot distribution the provider never
 *  produces, which is why the suite passed against a tolerance that rejected every live
 *  response. This fixture is shaped the way the live provider actually answers. */
const roundedPayload=()=>{const ids=c.map(x=>x.id).sort();const p=Object.fromEntries(ids.map((id,i)=>[id,i?.04:.34]));
  return {model:config.jevModel,answers:{next_action:{type:'choice',choice:ids[0],confidence:.62,probabilities:p}},usage:{input_tokens:18622,output_tokens:835}};};
test('provider-rounded distribution validates',()=>{const p=roundedPayload();const sum=Object.values(p.answers.next_action.probabilities).reduce((s,x)=>s+x,0);
  assert.ok(Math.abs(sum-1)>0.001,'fixture must not be exact to the old tolerance');
  assert.equal(validateResponse(p,c,config.jevModel).actionId,c.map(x=>x.id).sort()[0]);});
test('genuinely inconsistent distribution is still rejected',()=>{const p=roundedPayload();const ids=Object.keys(p.answers.next_action.probabilities);
  for(const id of ids.slice(1))p.answers.next_action.probabilities[id]=.1;
  assert.throws(()=>validateResponse(p,c,config.jevModel),/invalid_probability_sum/);});
