import test from'node:test';import assert from'node:assert/strict';import{generateKeyPairSync,sign}from'node:crypto';
import{openDb}from'../server/db.js';import{issueSession,hash,signLaunch,verifyLaunch,verifyDiscord,requireCsrf,RateLimiter}from'../server/security.js';
import{startOAuth,finishOAuth,redeemContext,handleInteraction}from'../server/auth.js';
const now=Date.now(),config={origin:'http://localhost:3000',discordClientId:'1234567890',discordClientSecret:'secret',launchKey:'a'.repeat(64),production:false};
const payload={v:1,aud:'jev-arcade',sub:'9876543210',guild_id:'5555555555',channel_id:'6666666666',game:'sudoku',iat:now,exp:now+600000,jti:'one-time-nonce'};
function user(db,id='9876543210'){db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(id,'Player',null,now,now);return issueSession(db,{userId:id}).row;}
test('signed launch rejects modification, expiration and wrong audience',()=>{const signed=signLaunch(payload,config.launchKey);assert.equal(verifyLaunch(signed,config.launchKey,now).sub,payload.sub);assert.throws(()=>verifyLaunch(signed.slice(0,-1)+'!',config.launchKey,now),/signature/);assert.throws(()=>verifyLaunch(signed,config.launchKey,now+600001),/expired/);assert.throws(()=>verifyLaunch(signLaunch({...payload,aud:'wrong'},config.launchKey),config.launchKey,now),/audience/);});
test('Discord Ed25519 verification binds timestamp and raw request bytes',()=>{const keys=generateKeyPairSync('ed25519'),raw=Buffer.from('{"type":1}'),timestamp=String(Math.floor(now/1000));const publicKey=keys.publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('hex');const signature=sign(null,Buffer.concat([Buffer.from(timestamp),raw]),keys.privateKey).toString('hex');assert.equal(verifyDiscord(raw,timestamp,signature,publicKey,now),true);assert.equal(verifyDiscord(Buffer.from('changed'),timestamp,signature,publicKey,now),false);assert.equal(verifyDiscord(raw,timestamp,signature,publicKey,now+400000),false);});
test('CSRF requires origin and session-bound token',()=>{const session={csrf:'a'.repeat(32)};assert.doesNotThrow(()=>requireCsrf({headers:{origin:config.origin,'x-csrf-token':session.csrf}},session,config.origin));assert.throws(()=>requireCsrf({headers:{origin:'https://evil.test','x-csrf-token':session.csrf}},session,config.origin));assert.throws(()=>requireCsrf({headers:{origin:config.origin,'x-csrf-token':'wrong'}},session,config.origin));});
test('rate limiter expires windows and bounds memory',()=>{const r=new RateLimiter(3);assert.equal(r.allow('a',1,100,0),true);assert.equal(r.allow('a',1,100,1),false);assert.equal(r.allow('a',1,100,101),true);for(let i=0;i<20;i++)r.allow('key'+i,1,100,1);assert.ok(r.buckets.size<=3);});
test('OAuth state, successful identity, rotated session and no token persistence',async()=>{const db=openDb(':memory:');try{const original=issueSession(db).row;const url=new URL(startOAuth(db,config,original));assert.equal(url.searchParams.get('scope'),'identify');const state=url.searchParams.get('state');let calls=0;const fakeFetch=async(url,options)=>{calls++;return Response.json(calls===1?{access_token:'do-not-store',refresh_token:'do-not-store-refresh'}:{id:'9876543210',username:'name',global_name:'Display <script>',avatar:null});};const issued=await finishOAuth(db,config,original,new URLSearchParams({state,code:'code'}),fakeFetch);assert.notEqual(issued.row.hash,original.hash);assert.equal(issued.row.user_id,'9876543210');assert.equal(db.prepare('SELECT 1 FROM sessions WHERE hash=?').get(original.hash),undefined);const rows=db.prepare('SELECT * FROM security_tokens').all();assert.equal(JSON.stringify(rows).includes('do-not-store'),false);await assert.rejects(finishOAuth(db,config,original,new URLSearchParams({state,code:'again'}),fakeFetch),/state_rejected/);}finally{db.close();}});
test('wrong-session or expired OAuth state is rejected before network access',async()=>{const db=openDb(':memory:');try{const a=issueSession(db).row,b=issueSession(db).row;const url=new URL(startOAuth(db,config,a)),params=new URLSearchParams({state:url.searchParams.get('state'),code:'test'});await assert.rejects(finishOAuth(db,config,b,params,()=>{throw new Error('must not call');}),/state/);db.prepare('UPDATE security_tokens SET expires_at=0').run();await assert.rejects(finishOAuth(db,config,a,params),/state/);}finally{db.close();}});
test('launch redemption is subject-bound, expiring and one-use',()=>{const db=openDb(':memory:');try{const s=user(db),other=user(db,'1111111111');db.prepare('INSERT INTO security_tokens(hash,kind,user_id,payload_json,expires_at) VALUES(?,?,?,?,?)').run(hash(payload.jti),'launch',payload.sub,'{}',payload.exp);const signed=signLaunch(payload,config.launchKey);assert.throws(()=>redeemContext(db,config,other,signed),/wrong_user/);const context=redeemContext(db,config,s,signed);assert.equal(context.guildId,payload.guild_id);assert.equal(context.channelId,payload.channel_id);assert.throws(()=>redeemContext(db,config,s,signed),/already_used/);}finally{db.close();}});
test('signed Discord command returns user-bound fragment link and rejects replay',()=>{const db=openDb(':memory:');try{const keys=generateKeyPairSync('ed25519'),cfg={...config,discordPublicKey:keys.publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('hex')};const input={id:'123123123123',application_id:config.discordClientId,type:2,data:{name:'jev',options:[{name:'sudoku',type:1}]},member:{user:{id:payload.sub}},guild_id:payload.guild_id,channel_id:payload.channel_id};const raw=Buffer.from(JSON.stringify(input)),ts=String(Math.floor(Date.now()/1000)),sig=sign(null,Buffer.concat([Buffer.from(ts),raw]),keys.privateKey).toString('hex');const req={headers:{'x-signature-timestamp':ts,'x-signature-ed25519':sig}};const result=handleInteraction(db,cfg,req,raw);assert.equal(result.data.flags,64);const url=new URL(result.data.components[0].components[0].url);assert.equal(url.search,'');const token=new URLSearchParams(url.hash.slice(1)).get('launch');assert.equal(verifyLaunch(token,cfg.launchKey).sub,payload.sub);assert.throws(()=>handleInteraction(db,cfg,req,raw),/replayed/);}finally{db.close();}});
