import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';
import{openDb,readMatch}from'../server/db.js';import{loadConfig}from'../server/config.js';import{MatchService}from'../server/matches.js';import{issueSession,hash}from'../server/security.js';import{leaderboard,operatorReport}from'../server/reports.js';import{createMatchState}from'../shared/match.js';import{replayEvents}from'../shared/replay.js';
const puzzle='004678912672195348198342567859761423426853791713924856961537284287419635345286179';
function setup({jev=false}={}){const db=openDb(':memory:'),config={...loadConfig({APP_ORIGIN:'http://localhost:3000',LAUNCH_SIGNING_KEY:'a'.repeat(64)}),jevKey:jev?'test-key':'',pacingMs:1000};let clock=Date.now(),mono=0;
  const fetchImpl=async(_,options)=>{const body=JSON.parse(options.body),ids=Object.keys(body.questions.next_action.criteria);return Response.json({model:config.jevModel,answers:{next_action:{type:'choice',choice:ids[0],confidence:1,probabilities:Object.fromEntries(ids.map((id,i)=>[id,i?0:1]))}},usage:{input_tokens:123,output_tokens:12}});};
  const svc=new MatchService(db,config,{autoTick:false,fetchImpl,now:()=>clock,monotonic:()=>mono});
  return{db,config,svc,advance:ms=>{clock+=ms;mono+=ms;},session:issueSession(db).row,close:()=>{svc.close();db.close();}};}
function insertMatch(x,{session=x.session,mode='practice',givens=puzzle,context=null}={}){const state=createMatchState(givens,{mode,pacingMs:1000,model:x.config.jevModel}),id=randomUUID();x.db.prepare('INSERT INTO matches(id,owner_hash,user_id,challenge_id,guild_id,channel_id,official,create_key,initial_json,state_json,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,session.hash,session.user_id,null,context?.guild||null,context?.channel||null,0,randomUUID(),JSON.stringify({givens,config:state.config}),JSON.stringify(state),'ready',Date.now());return id;}
const tick=()=>new Promise(r=>setImmediate(r));
test('start withholds initial clues until official start and verifies completed human replay',async()=>{const x=setup();try{const id=insertMatch(x);assert.equal(x.svc.project(x.svc.row(id)).givens,null);let p=x.svc.start(id,x.session);assert.equal(p.givens.length,81);x.advance(200);p=x.svc.action(id,x.session,{requestId:'first-move-1',expectedHumanRevision:0,action:{kind:'set',cell:0,digit:5}});x.advance(200);p=x.svc.action(id,x.session,{requestId:'second-move-1',expectedHumanRevision:1,action:{kind:'set',cell:1,digit:3}});assert.equal(p.phase,'settling');x.advance(700);x.svc.tick();p=x.svc.project(x.svc.row(id));assert.equal(p.phase,'finished');assert.equal(p.verified,true);const replay=x.svc.replay(id,x.session);assert.equal(replayEvents(replay).outcome,'human');assert.equal(x.db.prepare('SELECT COUNT(*) AS n FROM results').get().n,1);x.svc.finalize(x.svc.row(id));assert.equal(x.db.prepare('SELECT COUNT(*) AS n FROM results').get().n,1);}finally{x.close();}});
test('actions are owned, revision checked, idempotent and do not accept fabricated score fields',()=>{const x=setup();try{const id=insertMatch(x);x.svc.start(id,x.session);assert.throws(()=>x.svc.owned(id,issueSession(x.db).row),/owned/);const request={requestId:'duplicate-move',expectedHumanRevision:0,action:{kind:'set',cell:0,digit:5}};x.advance(50);x.svc.action(id,x.session,request);assert.equal(x.svc.action(id,x.session,request).human.revision,1);assert.throws(()=>x.svc.action(id,x.session,{...request,requestId:'new-move-123'}),/stale/);assert.throws(()=>x.svc.action(id,x.session,{...request,requestId:'forged-score',score:99999}),/unknown_request/);assert.throws(()=>x.svc.action(id,x.session,{requestId:'fabricated',expectedHumanRevision:1,action:{kind:'set',cell:1,digit:3,elapsedMs:1}}),/unknown_action/);}finally{x.close();}});
test('scheduler applies independent opponent steps and does not rely on client polling',async()=>{const x=setup({jev:true});try{const id=insertMatch(x);x.svc.start(id,x.session);await tick();x.advance(999);x.svc.tick();assert.equal(x.svc.row(id).state.jev.revision,0);x.advance(2);x.svc.tick();assert.equal(x.svc.row(id).state.jev.revision,1);await tick();x.advance(1001);x.svc.tick();assert.ok(x.svc.row(id).state.jev.finishMs!==null);assert.equal(x.svc.row(id).state.phase,'running');}finally{x.close();}});
test('ranked analytics and public projection do not leak opponent answers',async()=>{const x=setup({jev:true});try{const id=insertMatch(x,{mode:'ranked'});x.svc.start(id,x.session);await tick();x.advance(1001);x.svc.tick();const p=x.svc.project(x.svc.row(id));assert.equal(p.jev.hidden,true);assert.equal(p.decision.action,undefined);const a=x.svc.analytics(id,x.session);assert.equal(a.jev.decisions[0].digit,undefined);assert.equal(a.jev.decisions[0].candidateEvidence,undefined);assert.throws(()=>x.svc.replay(id,x.session),/after_finish/);const revealed=x.svc.reveal(id,x.session);assert.equal(revealed.eligibility,'practice');assert.equal(revealed.jev.hidden,false);}finally{x.close();}});
test('provider failure downgrades before the heuristic move',async()=>{const x=setup({jev:true});try{x.svc.adapter.fetch=async()=>new Response('',{status:401});const id=insertMatch(x,{mode:'ranked'});x.svc.start(id,x.session);await tick();x.advance(1001);x.svc.tick();const row=x.svc.row(id);assert.equal(row.state.eligibility,'practice');assert.equal(row.state.providerFallback,true);assert.equal(row.state.jev.revision,1);const events=x.db.prepare('SELECT event_json FROM match_events WHERE match_id=? ORDER BY sequence').all(id).map(r=>JSON.parse(r.event_json));assert.equal(events[1].type,'eligibility');assert.equal(events[2].decision.source,'heuristic_fallback');}finally{x.close();}});
test('restart recovery voids active attempts and verifies their stored state',()=>{const x=setup();try{const id=insertMatch(x);x.svc.start(id,x.session);x.advance(100);x.svc.recover();assert.equal(x.svc.row(id).state.eligibility,'void');assert.equal(x.svc.row(id).state.phase,'finished');assert.ok(x.db.prepare('SELECT 1 FROM results WHERE match_id=?').get(id));}finally{x.close();}});
test('official attempt reservation survives deletion as a short-lived keyed tombstone',()=>{const x=setup({jev:true});try{const now=Date.now(),date=new Date(now).toISOString().slice(0,10);x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run('9876543210','Player',null,now,now);const session=issueSession(x.db,{userId:'9876543210'}).row;x.db.prepare('INSERT INTO challenges VALUES(?,?,?,?,?,?,?,?)').run('daily-test',date,'normal',puzzle,hash(puzzle),'private-seed',JSON.stringify({model:x.config.jevModel}),now);const p=x.svc.create(session,{requestId:randomUUID(),mode:'ranked',difficulty:'normal'});x.db.prepare('DELETE FROM matches WHERE id=?').run(p.id);assert.throws(()=>x.svc.create(session,{requestId:randomUUID(),mode:'ranked',difficulty:'normal'}),/already_used/);const t=x.db.prepare("SELECT * FROM security_tokens WHERE kind='attempt'").get();assert.equal(t.user_id,null);assert.equal(t.payload_json,'{}');}finally{x.close();}});
test('channel/server/world leaderboards, tied ranks and pagination',()=>{const x=setup();try{const date=new Date().toISOString().slice(0,10),now=Date.now();x.db.prepare('INSERT INTO challenges VALUES(?,?,?,?,?,?,?,?)').run('daily',date,'normal',puzzle,hash(puzzle),'seed','{}',now);for(let i=0;i<4;i++){const uid=String(1000000000+i);x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(uid,'Player '+i,null,now,now);const s=issueSession(x.db,{userId:uid}).row,id=insertMatch(x,{session:s,context:{guild:i===3?'g2':'g1',channel:i===2?'c2':'c1'}});x.db.prepare('UPDATE matches SET challenge_id=?,status=? WHERE id=?').run('daily','finished',id);const seconds=i<2?10:11;x.db.prepare('INSERT INTO results VALUES(?,?,?,?,?,?,?,?,?)').run(id,1,'human',seconds*1000,seconds,null,'{}','hash',now);}
  const contextSession={user_id:'1000000000',context_json:JSON.stringify({guildId:'g1',channelId:'c1',userId:'1000000000',expiresAt:now+60000})};
  const p=new URLSearchParams({date,difficulty:'normal',scope:'world',limit:2});const page=leaderboard(x.db,null,p);assert.equal(page.entries.length,2);assert.deepEqual(page.entries.map(e=>e.rank),[1,1]);p.set('cursor',page.nextCursor);assert.deepEqual(leaderboard(x.db,null,p).entries.map(e=>e.rank),[3,3]);
  assert.equal(leaderboard(x.db,contextSession,new URLSearchParams({date,scope:'server'})).entries.length,3);assert.equal(leaderboard(x.db,contextSession,new URLSearchParams({date,scope:'channel'})).entries.length,2);assert.throws(()=>leaderboard(x.db,null,new URLSearchParams({scope:'channel',date})),/context/);
}finally{x.close();}});
test('operator reports make empty data and coverage explicit',()=>{const x=setup();try{const r=operatorReport(x.db);assert.equal(r.coverage.matches,0);assert.equal(r.summary.winRate,null);assert.equal(r.activity.authenticatedDAU,0);assert.equal(r.retention.length,0);assert.throws(()=>operatorReport(x.db,{days:0}),/days/);}finally{x.close();}});

test('expired ready reservations do not permanently block starting another game',()=>{
 const x=setup();try{const old=insertMatch(x);x.db.prepare('UPDATE matches SET created_at=? WHERE id=?').run(0,old);
 const next=x.svc.create(x.session,{requestId:'new-after-expired',mode:'practice',difficulty:'normal'});assert.notEqual(next.id,old);assert.equal(readMatch(x.db,old).state.eligibility,'void');
 }finally{x.close();}
});
