// Regenerates migrations/0002_practice_pool.sql: unique-solution practice puzzles, generated and verified offline so the
// Worker never has to run the generator. Deterministic (seeded), so the migration is reproducible. Ranked daily puzzles are
// NOT built here and are never committed; publish them with `npm run puzzles`.
import { writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { generatePuzzle } from './puzzle-lib.js';
import { countSolutions } from '../public/shared/sudoku.js';
const args = process.argv.slice(2), arg = (n, d) => { const i = args.indexOf(`--${n}`); return i < 0 ? d : args[i + 1]; };
const count = Number(arg('count', '300')), out = arg('out', 'migrations/0002_practice_pool.sql');
if (!Number.isInteger(count) || count < 1 || count > 5000) throw Error('Use --count 1..5000');
const rows = [], seen = new Set();
for (let i = 0; rows.length < count; i++) {
  const p = generatePuzzle(`practice-pool-v1:${i}`);
  if (countSolutions(p.givens, 2).count !== 1) throw Error(`puzzle ${i} is not unique`);
  const hash = createHash('sha256').update(p.givens).digest('hex');
  if (seen.has(hash)) continue; seen.add(hash);
  rows.push(`(${rows.length + 1},'${p.givens}','${hash}','${p.generatorVersion}')`);
}
writeFileSync(out, `-- Generated by scripts/build-pool.js (seeds practice-pool-v1:0..). Do not edit by hand; regenerate instead.\nINSERT OR IGNORE INTO puzzle_pool(id,givens,puzzle_hash,generator_version) VALUES\n${rows.join(',\n')};\n`);
console.log(`Wrote ${rows.length} puzzles to ${out}`);
