/** Isolated CLI smoke: never opens or modifies a real database. Exercises the local-database scripts end to end. */
import { mkdtempSync, rmSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { openDatabase } from '../local/database.js';
import { readMatch } from '../server/db.js';
import { createMatch, startMatch, humanAction } from '../server/matches.js';
import { issueSession } from '../server/security.js';
import { track } from '../server/telemetry.js';
const directory = mkdtempSync(join(tmpdir(), 'jev-maintenance-test-')), database = join(directory, 'sudoku.sqlite');
const env = { ...process.env, DATABASE_PATH: database, TELEMETRY_RETENTION_DAYS: '30', OPERATIONS_RETENTION_DAYS: '30' };
const checks = [];
const run = (file, args = []) => execFileSync(process.execPath, [file, ...args], { env, cwd: resolve('.'), encoding: 'utf8', timeout: 60000, stdio: ['ignore', 'pipe', 'pipe'] });
try {
  const worker = { DB: openDatabase(database), APP_ORIGIN: 'http://localhost:3000', LAUNCH_SIGNING_KEY: 'isolated-maintenance-test-key-00000000000000', PRACTICE_PACING_MS: '1000' };
  const session = (await issueSession(worker)).row;
  const match = await createMatch(worker, session, { requestId: 'maintenance-fixture', mode: 'practice', difficulty: 'normal' });
  await startMatch(worker, undefined, match.id, session);
  await track(worker, match.id, 'note_added', { cell: 0 }, 'client', 'old-note-fixture', Date.now() - 31 * 86400000);
  await humanAction(worker, undefined, match.id, session, { requestId: 'maintenance-forfeit', expectedHumanRevision: 0, action: { kind: 'forfeit' } });
  worker.DB.close();
  const published = run('scripts/puzzles.js', ['--date', '2030-01-01', '--days', '1']); assert.ok(published.includes('Published 4 new challenges'));
  const again = run('scripts/puzzles.js', ['--date', '2030-01-01', '--days', '1']); assert.ok(again.includes('Published 0 new challenges'));
  const sqlPath = join(directory, 'challenges.sql'); run('scripts/puzzles.js', ['--date', '2030-02-01', '--days', '1', '--sql', sqlPath]);
  const sql = readFileSync(sqlPath, 'utf8'); assert.equal(sql.trim().split('\n').length, 4); assert.ok(sql.startsWith('INSERT OR IGNORE INTO challenges'));
  checks.push('Four unique daily puzzles published locally; repeat publication does not overwrite; wrangler-ready SQL emitted without touching a database');
  const reportPath = join(directory, 'analytics.json'); run('scripts/analytics.js', ['--match', match.id, '--out', reportPath]);
  const report = JSON.parse(readFileSync(reportPath)); assert.equal(report.schemaVersion, 'analytics-v1'); assert.equal(report.human.forfeits, 1);
  const csv = run('scripts/analytics.js', ['--match', match.id, '--format', 'csv']); assert.ok(csv.startsWith('"sequence","ms"'));
  const operator = JSON.parse(run('scripts/analytics.js', ['--days', '30'])); assert.equal(operator.coverage.matches, 1);
  checks.push('Finished-match JSON, decision CSV and operator JSON CLI exports');
  const sweepResult = JSON.parse(run('scripts/maintenance.js', ['--sweep'])); assert.ok(sweepResult.sweep.purged >= 1);
  const after = openDatabase(database);
  assert.ok(await readMatch({ DB: after }, match.id));
  assert.equal((await after.prepare("SELECT COUNT(*) AS n FROM telemetry WHERE trust='client'").first()).n, 0); after.close();
  checks.push('Expired optional telemetry purged by the lazy sweep; core game and verified result retained');
  const backupPath = join(directory, 'backup.sqlite'); run('scripts/maintenance.js', ['--backup', backupPath]);
  const backup = openDatabase(backupPath);
  assert.equal((await backup.prepare('PRAGMA integrity_check').first()).integrity_check, 'ok'); assert.equal((await backup.prepare('PRAGMA foreign_key_check').all()).results.length, 0);
  assert.equal((await backup.prepare('SELECT COUNT(*) AS n FROM results').first()).n, 1); backup.close();
  assert.throws(() => run('scripts/maintenance.js', ['--backup', backupPath]));
  checks.push('Consistent backup reopened and checked; overwrite refused');
  const integrity = JSON.parse(run('scripts/maintenance.js', ['--integrity'])); assert.equal(integrity.integrity[0].integrity_check, 'ok'); assert.equal(integrity.foreignKeys.length, 0);
  checks.push('Live test database integrity and foreign-key checks pass');
  const result = { suite: 'Isolated CLI and SQLite maintenance smoke', generatedAt: new Date().toISOString(), passed: checks.length, failed: 0, checks,
    limitations: 'Temporary local fixture database only. Cloudflare D1, wrangler, remote backups and live restoration were not exercised.' };
  mkdirSync('reports/workers', { recursive: true }); writeFileSync('reports/workers/maintenance-results.json', JSON.stringify(result, null, 2) + '\n'); console.log(JSON.stringify(result, null, 2));
} finally { rmSync(directory, { recursive: true, force: true }); }
